# Site settings
title: Ian Huang
email: f06942135@ntu.edu.tw
description: > # this means to ignore newlines until "baseurl:"
  Ph.D. Student at National Taiwan University.
baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://www.domoritz.de" # the base hostname & protocol for your site
# production_url: "https://www.domoritz.de"
github_username: ianhuang2664
permalink: /blog/:year/:month/:title.html

twitter:
  username: ian_huang2664

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
